In [15]:
from bauer.models import RiskModel
import numpy as np
import pandas as pd

n_subjects = 10

parameters = {'risky_prior_mu':np.log(50), 'risky_prior_std':1.0, 'safe_prior_mu':np.log(14), 'safe_prior_std':2.0, 'n1_evidence_sd':0.4, 'n2_evidence_sd':0.2}


parameters = pd.DataFrame([parameters]*n_subjects, index=pd.Index(np.arange(1, n_subjects+1), name='subject'))

model = RiskModel(fit_seperate_evidence_sd=True, prior_estimate='full')
parameters = model.sample_parameters_from_prior(n_subjects)

paradigm = model.get_example_paradigm(n_subjects=n_subjects)


df = model.simulate(paradigm, parameters, n_samples=1)
df['choice'] = df['simulated_choice']
df['chose_risky'] = df['choice'].where(~df['risky_first'], ~df['choice'])

In [17]:
df.loc[1].shape

(96, 11)

In [13]:
model.build_estimation_model(df)

In [14]:
idata = model.sample()

Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [n1_evidence_sd_mu_untransformed, n1_evidence_sd_sd, n1_evidence_sd_offset, n2_evidence_sd_mu_untransformed, n2_evidence_sd_sd, n2_evidence_sd_offset, risky_prior_mu_mu, risky_prior_mu_sd, risky_prior_mu_offset, risky_prior_std_mu_untransformed, risky_prior_std_sd, risky_prior_std_offset, safe_prior_mu_mu, safe_prior_mu_sd, safe_prior_mu_offset, safe_prior_std_mu_untransformed, safe_prior_std_sd, safe_prior_std_offset]

Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 34 seconds.
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
There were 39 divergences after tuning. Increase `target_accept` or reparameterize.

In [16]:
sns.catplot(x='log(risky/safe)', y='choice')

                      simulated_choice  n_safe  fraction  risky_first     n1  \
subject trial sample
1       1     1                   True     5.0  0.250000         True    1.0
        2     1                  False     5.0  0.250000        False    5.0
        3     1                   True     5.0  0.371499         True    2.0
        4     1                  False     5.0  0.371499        False    5.0
        5     1                   True     5.0  0.552045         True    3.0
...                                ...     ...       ...          ...    ...
100     92    1                  False    28.0  1.811447        False   28.0
        93    1                   True    28.0  2.691800         True   75.0
        94    1                   True    28.0  2.691800        False   28.0
        95    1                  False    28.0  4.000000         True  112.0
        96    1                   True    28.0  4.000000        False   28.0

                         n2    p1    p2
subject trial sample
1       1     1         5.0  0.55  1.00
        2     1         1.0  1.00  0.55
        3     1         5.0  0.55  1.00
        4     1         2.0  1.00  0.55
        5     1         5.0  0.55  1.00
...                     ...   ...   ...
100     92    1        51.0  1.00  0.55
        93    1        28.0  0.55  1.00
        94    1        75.0  1.00  0.55
        95    1        28.0  0.55  1.00
        96    1       112.0  1.00  0.55

[9600 rows x 8 columns]

In [2]:
paradigm

               n_safe  fraction  risky_first     n1     n2    p1    p2
subject trial
1       1         5.0  0.250000         True    1.0    5.0  0.55  1.00
        2         5.0  0.250000        False    5.0    1.0  1.00  0.55
        3         5.0  0.371499         True    2.0    5.0  0.55  1.00
        4         5.0  0.371499        False    5.0    2.0  1.00  0.55
        5         5.0  0.552045         True    3.0    5.0  0.55  1.00
...               ...       ...          ...    ...    ...   ...   ...
100     92       28.0  1.811447        False   28.0   51.0  1.00  0.55
        93       28.0  2.691800         True   75.0   28.0  0.55  1.00
        94       28.0  2.691800        False   28.0   75.0  1.00  0.55
        95       28.0  4.000000         True  112.0   28.0  0.55  1.00
        96       28.0  4.000000        False   28.0  112.0  1.00  0.55

[9600 rows x 7 columns]

In [ ]:
paradigm